#!/usr/bin/env zsh

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000

setopt appendhistory autocd beep extendedglob nomatch notify

# emacs key bindings
bindkey -e

## completion
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit

# enable completion interface
zstyle ':completion:*' menu select

# completion on privliged
zstyle ':completion::complete:*' gain-privileges 1

# completion of aliases
setopt COMPLETE_ALIASES

## prompt
autoload -Uz promptinit
promptinit

# general aliases
alias b='~/blender-git/build/bin/blender'
alias e='emacs -nw'
alias g='git'
alias v='vim'
alias mkdir='mkdir -pv'
alias df='df -h'
alias l='ls --color=auto'
alias ll='ls -altr --color=auto'

# vagrant aliases
alias vs='vagrant ssh'
alias vu='vagrant up'
alias vus='vagrant up && vagrant ssh'
alias vh='vagrant halt'
alias vg='vagrant global-status'
alias vr='vagrant reload'
alias vrp='vagrant reload --provision'

# pacman aliases
alias pacupg='sudo pacman -Syu'		# Synchronize with repositories and then upgrade packages that are out of date on the local system.
alias pacdl='pacman -Sw'		# Download specified package(s) as .tar.xz ball
alias pacin='sudo pacman -S'		# Install specific package(s) from the repositories
alias pacins='sudo pacman -U'		# Install specific package not from the repositories but from a file
alias pacre='sudo pacman -R'		# Remove the specified package(s), retaining its configuration(s) and required dependencies
alias pacrem='sudo pacman -Rns'		# Remove the specified package(s), its configuration(s) and unneeded dependencies
alias pacrep='pacman -Si'		# Display information about a given package in the repositories
alias pacreps='pacman -Ss'		# Search for package(s) in the repositories
alias pacloc='pacman -Qi'		# Display information about a given package in the local database
alias paclocs='pacman -Qs'		# Search for package(s) in the local database
alias paclo='pacman -Qdt'		# List all packages which are orphaned
alias pacc='sudo pacman -Scc'		# Clean cache - delete all the package files in the cache
alias paclf='pacman -Ql'		# List all files installed by a given package
alias pacown='pacman -Qo'		# Show package(s) owning the specified file(s)
alias pacexpl='pacman -D --asexp'	# Mark one or more installed packages as explicitly installed
alias pacimpl='pacman -D --asdep'	# Mark one or more installed packages as non explicitly installed

# Additional pacman alias
alias pacupd='sudo pacman -Sy && sudo abs'         # Update and refresh the local package and ABS databases against repositories
alias pacinsd='sudo pacman -S --asdeps'            # Install given package(s) as dependencies
alias pacmir='sudo pacman -Syy'                    # Force refresh of all package lists after updating /etc/pacman.d/mirrorlist

# macos/bbc
if [[ `uname` = 'Darwin' ]]
then
   source /usr/local/share/antigen/antigen.zsh
   source /usr/local/bin/proxy-toggle.sh

   alias l='ls -G'
   alias ll='ls -altrG'
fi

# install packages
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

# pure prompt
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply
